# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing JEST...
      - npm install -g jest
  pre_build:
    commands:
      - echo Installing source NPM dependencies ...
      - npm install
      - echo Installing SonarScanner...
      - curl -L -o sonarscanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
      - unzip sonarscanner.zip
      - rm sonarscanner.zip
      - export PATH="$PATH:$PWD/sonar-scanner-4.6.2.2472-linux/bin"
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run test
      - echo Running code analysis with SonarQube...
#       - sonar-scanner \
#           -Dsonar.projectKey=sample-app \
#           -Dsonar.sources=. \
#           -Dsonar.host.url=http://3.108.50.135 \
#           -Dsonar.login=sqp_28b5663d94cc65f46e64c23c27b3fc89767fdd2e

  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - app.js
    - package.json
    - node_modules/*

